---
# Playbook for Kali

## Update Kali and deploy packages
- hosts: kali
  become: true
  tasks:
    - name: Ensure apt-transport-https package is installed
      apt:
        name: apt-transport-https
        state: present
    
    - name: Configure sources.list to use HTTPS
      replace:
        path: /etc/apt/sources.list
        regexp: '^(deb\s+)http(://http.kali.org/kali.*)$'
        replace: '\1https\2'

    - name: Update all packages to the latest version
      apt:
        update_cache: true
        upgrade: safe

    - name: Enable Wireshark setuid debconf selection
      debconf:
        name: wireshark
        question: wireshark-common/install-setuid
        value: 'true'
        vtype: boolean 

    - name: Install Kali packages
      apt:
        name: "{{ kali_packages }}"
        state: present
    
    - name: Remove unnecessary packages
      apt:
        autoremove: true

    - name: Clean apt cache
      apt:
        autoclean: true

    - name: Install Python Pip Packages
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      loop: "{{ python_pip_packages }}"

    - name: Install Ruby Gem Packages
      gem:
        name: "{{ item }}"
        state: latest
        user_install: false
      loop: "{{ ruby_gem_packages }}"
