---
# Playbook for Kali

# Deploy tools not found in the Kali repositories
- hosts: kali
  become: true
  tasks:
    - name: Install Burp Suite
      ansible.builtin.include_role:
        name: "ansible-role-burpsuite"

    - name: Create .burpsuitepro_licensed after successful Pro install
      ansible.builtin.file:
        path: "{{ kali_user_details.home }}/.burpsuitepro_licensed"
        state: touch
      when: 'burpsuite_product_type == "pro"'

    - name: Install Keystone Engine
      ansible.builtin.include_role:
        name: "ansible-role-keystone-engine"

    - name: Install MS Visual Studio Code
      ansible.builtin.include_role:
        name: "ansible-role-vscode"

    # Clone git repos
    - name: Clone git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
        depth: 1
        force: true
      loop: "{{ git_repos | flatten(levels=1) }}"

    # Miscellaneous tools
    - name: Ensure destination directory exists
      ansible.builtin.file:
        dest: "{{ item.dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ misc_downloads }}"
            
    - name: Download files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode | default('0644') }}"
      loop: "{{ misc_downloads }}"
    
    ### CyberChef ###
    - name: Creates cyberchef directory
      file:
        dest: /var/www/html/cyberchef/
        state: directory
        owner: root
        group: root
        mode: 655

    - name: Download and unarchive CyberChef
      unarchive:
        src: https://github.com/gchq/CyberChef/releases/download/v9.37.3/CyberChef_v9.37.3.zip
        dest: /var/www/html/cyberchef/
        remote_src: yes

    - name: Create a symbolic link - CyberChef
      file:
        src: /var/www/html/cyberchef/CyberChef_v9.37.3.html
        dest: /var/www/html/cyberchef.htm
        owner: root
        group: root
        state: link