---
- name: User choices
  hosts: localhost
  vars:
    burpsuite_products_map:
      - { name: Burp Suite Community, alias: community }
      - { name: Burp Suite Professional, alias: pro }
  tasks:
    - name: Check if config.yml exists
      stat:
        path: config.yml
      register: config_yml

    - name: Load config.yml
      include_vars: config.yml
      when: config_yml.stat.exists

    - block:
        - name: Burp Suite edition prompt
          pause:
            prompt: |
              What Burp Suite product would you like to install?
                {% for p in burpsuite_products_map %}
                {{ loop.index }}. {{ p['name'] }}
                {% endfor %}

              Enter the number for the product
          register: _burpsuite_choice

        - name: Set fact
          set_fact:
            burpsuite_product_type: "{{ burpsuite_products_map[_burpsuite_choice.user_input|default(omit)|int - 1]['alias'] }}"
      when: burpsuite_product_type is undefined

    - name: Save config
      template:
        src: templates/config/config.yml.j2
        dest: ./config.yml
        mode: 0600
      delegate_to: localhost

    - name: Set cacheable facts
      set_fact:
        burpsuite_product_type: "{{ burpsuite_product_type }}"
        cacheable: true

- name: Include Kali packages playbook
  import_playbook: kali-packages.yml

- name: Include Kali tools playbook
  import_playbook: kali-tools.yml

- name: Include Kali configuration playbook
  import_playbook: kali-config.yml

- name: Include Kali personalization playbook
  import_playbook: kali-personalize.yml
