---
# Burp Suite settings
burpsuite_dir: "/opt/BurpSuite{{ burpsuite_product_type | capitalize }}"
burpsuite_extras_cacert_path: "{{ burpsuite_extras_dir }}/PortSwigger_CA.der"
burpsuite_extras_dir: /opt/BurpSuiteExtras
burpsuite_installer_dir: "/home/{{ kali_user }}/Downloads"
burpsuite_user: "{{ kali_user }}"

# XFCE settings
xfce_settings:
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/blank-on-ac", type: "int", value: "30" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/dpms-enabled", type: "bool", value: "true" }  
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/dpms-on-ac-off", type: "int", value: "0" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/dpms-on-ac-sleep", type: "int", value: "0" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/general-notification", type: "bool", value: "false" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/inactivity-on-ac", type: "int", value: "14" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/inactivity-sleep-mode-on-ac", type: "int", value: "1" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/lock-screen-suspend-hibernate", type: "bool", value: "true" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/logind-handle-lid-switch", type: "bool", value: "false" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/power-button-action", type: "int", value: "4" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/show-tray-icon", type: "bool", value: "false" }
  - { channel: "xfwm4", property: "/general/vblank_mode", type: "string", value: "xpresent" }
  - { channel: "xfwm4", property: "/general/workspace_count", type: "int", value: "4" }

# Git repositories to clone to /opt
git_repos:
  - name: fuzzdb
    repo: https://github.com/fuzzdb-project/fuzzdb.git
  - name: Inveigh
    repo: https://github.com/Kevin-Robertson/Inveigh.git
  - name: PayloadsAllTheThings
    repo: https://github.com/swisskyrepo/PayloadsAllTheThings.git
  - name: Powermad
    repo: https://github.com/Kevin-Robertson/Powermad.git
  - name: PowerSploit
    repo: https://github.com/PowerShellMafia/PowerSploit.git
    version: dev
  - name: privilege-escalation-awesome-scripts-suite
    repo: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite.git
  - name: quieter-firefox
    repo: https://bitbucket.org/mrbbking/quieter-firefox.git
  - name: SecLists
    repo: https://github.com/danielmiessler/SecLists.git

# Packages for OS
kali_os_packages:
  - apparmor
  - apt-transport-https
  - build-essential
  - cmake
  - default-mysql-client
  - dnsutils
  - docker.io
  - docker-compose
  - dos2unix
  - expect
  - fonts-hack-ttf
  - golang
  - gufw
  - keepassxc
  - libffi-dev
  - libssl-dev
  - macchanger
  - openresolv
  - open-vm-tools-desktop
  - php
  - postgresql
  - python3
  - python3-dev
  - python3-pip
  - python3-setuptools
  - realtek-rtl88xxau-dkms
  - ruby
  - scite
  - screen
  - sqlite3
  - ufw
  - wireguard
  - xclip
  - xsel

# Tool packages to install
kali_tool_packages:
  - aircrack-ng
  - amass
  - apache2
  - bloodhound
  - cadaver
  - cewl
  - chromium
  - crackmapexec
  - creddump7
  - dirb
  - dnsrecon
  - exe2hexbat
  - exploitdb
  - eyewitness
  - freerdp2-x11
  - gdb
  - gdbserver
  - gobuster
  - gpp-decrypt
  - hash-identifier
  - hydra
  - john
  - joplin
  - masscan
  - metasploit-framework
  - nasm
  - nbtscan-unixwiz
  - ncat
  - neo4j
  - netcat-traditional
  - netdiscover
  - nikto
  - nmap
  - onesixtyone
  - parallel
  - passing-the-hash
  - patator
  - powershell
  - proxychains4
  - python3-impacket
  - responder
  - rlwrap
  - smbclient
  - smbmap
  - socat
  - sqlmap
  - sslscan
  - sslyze
  - wafw00f
  - webshells
  - weevely
  - wfuzz
  - whatweb
  - wifiphisher
  - windows-binaries
  - wireshark
  - wpscan
  - xtightvncviewer

python_pip_packages:
  - bloodhound
  - mitm6

ruby_gem_packages:
  - evil-winrm

kali_user: hacker

misc_downloads:
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64
    dest: /opt/pspy/pspy64
    mode: "0755"
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64s
    dest: /opt/pspy/pspy64s
    mode: "0755"

# Extensions for VS Code
vscode_extensions:
  # Language extensions
  - ms-python.python
  - ms-vscode.cpptools
  - ms-vscode.powershell
  - rebornix.ruby
  # Markdown extensions
  - yzhang.markdown-all-in-one
  - telesoho.vscode-markdown-paste-image
  # Utility extensions
  - hookyqr.beautify
