---
# Burp Suite settings
burpsuite_dir: "/opt/BurpSuite{{ burpsuite_product_type | capitalize }}"
burpsuite_extras_cacert_path: "{{ burpsuite_extras_dir }}/PortSwigger_CA.der"
burpsuite_extras_dir: /opt/BurpSuiteExtras
burpsuite_extras_pro_license_path: "{{ burpsuite_installer_dir }}/burpsuite_pro_license.txt"
burpsuite_installer_dir: "/home/{{ kali_user }}/Downloads"
burpsuite_user: "{{ kali_user }}"

# XFCE settings
xfce_settings:
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/blank-on-ac", type: "int", value: "30" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/dpms-enabled", type: "bool", value: "true" }  
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/dpms-on-ac-off", type: "int", value: "0" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/dpms-on-ac-sleep", type: "int", value: "0" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/general-notification", type: "bool", value: "false" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/inactivity-on-ac", type: "int", value: "14" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/inactivity-sleep-mode-on-ac", type: "int", value: "1" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/lock-screen-suspend-hibernate", type: "bool", value: "true" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/logind-handle-lid-switch", type: "bool", value: "false" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/power-button-action", type: "int", value: "4" }
  - { channel: "xfce4-power-manager", property: "/xfce4-power-manager/show-tray-icon", type: "bool", value: "false" }
  - { channel: "xfwm4", property: "/general/vblank_mode", type: "string", value: "xpresent" }
  - { channel: "xfwm4", property: "/general/workspace_count", type: "int", value: "4" }

# Git repositories to clone to /opt
git_repos:
  - name: PayloadsAllTheThings
    repo: https://github.com/swisskyrepo/PayloadsAllTheThings.git
  - name: privilege-escalation-awesome-scripts-suite
    repo: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite.git
  - name: quieter-firefox
    repo: https://bitbucket.org/mrbbking/quieter-firefox.git
  - name: SecLists
    repo: https://github.com/danielmiessler/SecLists.git

# Packages for OS
kali_os_packages:
  - apt-transport-https
  - cmake
  - gufw
  - kali-linux-default
  - libssl-dev
  - realtek-rtl88xxau-dkms
  - ufw
  - wireguard
  - xclip
  - xsel

# Tool packages to install
kali_tool_packages:
  - bloodhound
  - chromium
  - eyewitness
  - gdb
  - gdbserver
  - gobuster
  - joplin
  - keepassxc
  - libreoffice
  - nbtscan-unixwiz
  - ncat
  - neo4j
  - parallel
  - powershell
  - proxychains4
  - rlwrap
  - scite

python_pip_packages:
  - bloodhound
  - crackmapexec
  - mitm6
  - pwntools

ruby_gem_packages:
  - winrm
  - winrm-fs
  - stringio
  - evil-winrm

# Set as the user account that runs the ansible playbook
kali_user: "{{ lookup('env','USER') }}"

misc_downloads:
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64
    dest: /opt/pspy/pspy64
    mode: "0755"
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64s
    dest: /opt/pspy/pspy64s
    mode: "0755"

# Extensions for VS Code
vscode_extensions:
  # Language extensions
  - ms-python.python
  - ms-vscode.cpptools
  - ms-vscode.powershell
  # Markdown extensions
  - yzhang.markdown-all-in-one
  # Utility extensions
  - esbenp.prettier-vscode
